name: Release

on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Call CI workflow
        uses: ./.github/workflows/ci.yml
        with:
          run_tests: true

      - name: Build package
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install --upgrade pip build
          python -m build

      - name: Publish to Nexus (Dummy)
        env:
          NEXUS_USER: ${{ secrets.NEXUS_USER }}
          NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
        run: |
          echo "Publishing to Nexus..."
          echo "Dummy upload: user=$NEXUS_USER, password=$NEXUS_PASSWORD"
          # Echte Befehle könnten twine upload --repository-url ... sein
